// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server_Side.Model;

#nullable disable

namespace ServerSide.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20230116210514_hotfix")]
    partial class hotfix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server_Side.Model.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("Username");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("57b3820d-1efb-4722-9a85-2cbbc8ae1be1"),
                            CreatedByUsername = "admin",
                            CreatedDate = new DateTime(2023, 1, 16, 16, 5, 14, 103, DateTimeKind.Local).AddTicks(3420),
                            CustomerName = "Kroger",
                            Type = 0
                        },
                        new
                        {
                            OrderId = new Guid("f916d998-f731-4384-9a0b-8269c574f679"),
                            CreatedByUsername = "user",
                            CreatedDate = new DateTime(2023, 1, 16, 16, 5, 14, 103, DateTimeKind.Local).AddTicks(3450),
                            CustomerName = "Taget",
                            Type = 1
                        },
                        new
                        {
                            OrderId = new Guid("71a4b3e2-8aa5-43d2-8f9c-88f3b58029ee"),
                            CreatedByUsername = "admin3",
                            CreatedDate = new DateTime(2023, 1, 16, 16, 5, 14, 103, DateTimeKind.Local).AddTicks(3452),
                            CustomerName = "Apple",
                            Type = 2
                        },
                        new
                        {
                            OrderId = new Guid("09a38f39-ff12-428c-8f53-e1f84bae6e1e"),
                            CreatedByUsername = "admin4",
                            CreatedDate = new DateTime(2023, 1, 16, 16, 5, 14, 103, DateTimeKind.Local).AddTicks(3455),
                            CustomerName = "Microsoft",
                            Type = 3
                        },
                        new
                        {
                            OrderId = new Guid("5895d84c-1cfe-4167-860c-40ebe4a516c9"),
                            CreatedByUsername = "admin5",
                            CreatedDate = new DateTime(2023, 1, 16, 16, 5, 14, 103, DateTimeKind.Local).AddTicks(3458),
                            CustomerName = "Google",
                            Type = 4
                        });
                });

            modelBuilder.Entity("Server_Side.Model.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "admin",
                            FirstName = "Bryan",
                            LastName = "Rodriguez",
                            PasswordHash = "admin",
                            PermissionLevel = 3,
                            PhoneNumber = "8126972996"
                        },
                        new
                        {
                            Username = "user",
                            FirstName = "Bryan",
                            LastName = "Rodriguez",
                            PasswordHash = "admin",
                            PermissionLevel = 1,
                            PhoneNumber = "8126972996"
                        },
                        new
                        {
                            Username = "admin3",
                            FirstName = "Bryan",
                            LastName = "Rodriguez",
                            PasswordHash = "admin",
                            PermissionLevel = 3,
                            PhoneNumber = "8126972996"
                        },
                        new
                        {
                            Username = "admin4",
                            FirstName = "Bryan",
                            LastName = "Rodriguez",
                            PasswordHash = "admin",
                            PermissionLevel = 3,
                            PhoneNumber = "8126972996"
                        },
                        new
                        {
                            Username = "admin5",
                            FirstName = "Bryan",
                            LastName = "Rodriguez",
                            PasswordHash = "admin",
                            PermissionLevel = 3,
                            PhoneNumber = "8126972996"
                        });
                });

            modelBuilder.Entity("Server_Side.Model.Order", b =>
                {
                    b.HasOne("Server_Side.Model.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("Username");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server_Side.Model.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
